### ISSUE TITLE
Add more unit tests to cover edge-case-scenarios

### ISSUE THREAD

**Issue by nomemory** [nomemory/aleph-formatter#6]

**Comment by arjvik** [comment]
What sort of edge-case scenarios do you have in mind?

**Comment by nomemory** [comment]
@arjvik 

If we analyse the test coverage the library doesn't look great.

When I refer to edge-case scenarios I refer testing the library with "extreme strings" - multiple escape characters one to another, weird expressions inside the `#{}`, null values supplied to the methods for the api, etc.
