### ISSUE TITLE
Can't find a "style" method

### ISSUE THREAD

**Issue by victory-glitch** [nomemory/aleph-formatter#8]
Hi, I'm using v0.1.0 of the library but I can't find any style method to use on the str to support $ sign formatting. Is there a class missing from the jar?

**Comment by arjvik** [comment]
@hareharey I wrote the style methods almost two years ago. At the time @nomemory had not uploaded a new revision to bintray yet, so I had to make my own unofficial build.

You can download my build from [here](https://github.com/ArjMart/ArjMartDialogflowWebhook/blob/master/WebContent/WEB-INF/lib/aleph-formatter-unofficial-build.jar).

@nomemory, when you get a chance, can you push the latest revision to bintray?

**Comment by victory-glitch** [comment]
@arjvik awesome, thanks for the explanation. 

I'm using this jar as part of some code in an internal-facing application I'm developing for work, but my company only allows me to use jars that are officially deployed to mavenrepo/jcenter. I'll have to wait until @nomemory pushes up a new revision.

**Comment by nomemory** [comment]
@arjvik @hareharey 

I have pushed a new version on bintray.
Can you please see if everything works ok ?

**Comment by victory-glitch** [comment]
@nomemory Yep, it seems to work now, thanks!
