### ISSUE TITLE
Create a property to define the default style

### ISSUE THREAD

**Issue by victory-glitch** [nomemory/aleph-formatter#9]
Hi,
When I am creating format strings, I always set all the strings to use `${...}` formatting. Unfortunately, this requires me to put `.style(Styles.DOLLARS)` at the end of every string I'm formatting, which is repetitive and annoying.

Can you please define a property that we can set so AlephFormatter knows to always pick $-style formatting? Or, could you add a setter method to the class that we can call to set the formatting style prior to executing any fmt() commands? (or do both?)

**Comment by arjvik** [comment]
@hareharey:
@nomemory and I discussed this when creating the `.style()` method. Originally, I wanted to turn the style into a global variable, but @nomemory pointed out that two different libraries which used different interpolation styles would cause conflicts. Making it global or using a property file would cause issues like that.

Maybe you can create a wrapper method which takes the same parameters as the static `str()` method:
```java
public class AlephExtensions {
    public static AlephFormatter str(String str, Object... args) {
        AlephFormatter af = new AlephFormatter(str, args);
        return af.style(Styles.DOLLARS);
    }
}
```

**Comment by nomemory** [comment]
That's actually a very good idea I've already explored.
The plan was to keep a /resources/aleph.properies file that contains this kind of configuration.

@arjvik are you interested in developing this?

Andrei
